<?php

/**
 * @file
 * Test module for the entity API providing several entity types for testing.
 */

/**
 * Implements hook_entity_view_mode_info_alter().
 */
function devel_test_entity_view_mode_info_alter(&$view_modes) {
  $entity_info = \Drupal::entityManager()->getDefinitions();
  foreach ($entity_info as $entity_type => $info) {
    if ($entity_info[$entity_type]->getProvider() == 'devel_entity_test_canonical' && !isset($view_modes[$entity_type])) {
      $view_modes[$entity_type] = array(
        'full' => array(
          'label' => t('Full object'),
          'status' => TRUE,
          'cache' => TRUE,
        ),
        'teaser' => array(
          'label' => t('Teaser'),
          'status' => TRUE,
          'cache' => TRUE,
        ),
      );
    }
  }
}

/**
 * Implements hook_file_download().
 */
function devel_test_file_download($uri) {
  $default_uri = \Drupal::state()->get('devel.test_file_download') ?: FALSE;
  if ($default_uri === $uri) {
    return array('X-Owned-By' => 'devel_test');
  }
}
